#!/usr/bin/env python3
"""
CNN Market Order Sweep — Test market entries through Rust MBO Sim
================================================================
Uses the SAME predictions already generated by cnn_rust_sim_validation.py
but runs with --market-entry flag (cross the spread, 100% fill rate).

This tests whether the CNN signal edge survives the cost of crossing.

Usage:
    python alpha_discovery/cnn_market_order_sweep.py
    python alpha_discovery/cnn_market_order_sweep.py --workers 8
"""

import sys
import json
import time
import logging
import argparse
import subprocess
import numpy as np
from pathlib import Path
from datetime import datetime
from concurrent.futures import ThreadPoolExecutor, as_completed

LVL3_ROOT = Path(__file__).resolve().parent.parent

BINARY = LVL3_ROOT / 'rust_cache_builder' / 'target' / 'release' / 'fill_sim_cli.exe'
MBO_DIR = LVL3_ROOT / 'mbo'
RESULTS_DIR = LVL3_ROOT / 'alpha_discovery' / 'results'
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

# Reuse predictions from CNN passive sim
PRED_DIR = LVL3_ROOT / 'data' / 'processed' / 'cnn_sim_predictions'
SIM_OUT_DIR = LVL3_ROOT / 'data' / 'processed' / 'cnn_market_sim_results'
SIM_OUT_DIR.mkdir(parents=True, exist_ok=True)

TICK_VALUE = 12.50

_ts = datetime.now().strftime('%Y%m%d_%H%M%S')
_log_file = str(RESULTS_DIR / f'cnn_market_sweep_{_ts}.log')

log = logging.getLogger('cnn_market_sweep')
log.setLevel(logging.INFO)
_fh = logging.FileHandler(_log_file, mode='w', encoding='utf-8')
_fh.setFormatter(logging.Formatter('%(asctime)s %(levelname)s: %(message)s'))
log.addHandler(_fh)
_ch = logging.StreamHandler(sys.stdout)
_ch.setFormatter(logging.Formatter('%(asctime)s %(levelname)s: %(message)s'))
log.addHandler(_ch)

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')

# Market order configs — test various thresholds and hold times
# Higher thresholds matter MORE here because we pay spread on entry
MARKET_CONFIGS = [
    # (threshold, hold_ms, latency_ms, trailing_ticks, label)
    # 30min hold (proven best horizon)
    (1.0, 1800000, 0, 0, 'mkt_conv10_30min'),
    (1.5, 1800000, 0, 0, 'mkt_conv15_30min'),
    (2.0, 1800000, 0, 0, 'mkt_conv20_30min'),
    (2.5, 1800000, 0, 0, 'mkt_conv25_30min'),
    (3.0, 1800000, 0, 0, 'mkt_conv30_30min'),

    # With latency (more realistic)
    (1.5, 1800000, 10, 0, 'mkt_conv15_30min_lat10'),
    (2.0, 1800000, 10, 0, 'mkt_conv20_30min_lat10'),
    (2.5, 1800000, 10, 0, 'mkt_conv25_30min_lat10'),

    # 10min hold
    (1.5, 600000, 0, 0, 'mkt_conv15_10min'),
    (2.0, 600000, 0, 0, 'mkt_conv20_10min'),
    (2.5, 600000, 0, 0, 'mkt_conv25_10min'),

    # With trailing stops (may work better with guaranteed fills)
    (1.5, 1800000, 0, 8, 'mkt_conv15_30min_trail8'),
    (2.0, 1800000, 0, 8, 'mkt_conv20_30min_trail8'),
    (2.0, 1800000, 0, 12, 'mkt_conv20_30min_trail12'),
]

VOL_GATES = [50, 70, 80]
TIME_FILTERS = ['morning_afternoon']


def load_prediction_files():
    """Load existing prediction files from CNN sim.
    Filename format: 2025-08-19_vol50_morning_afternoon.npz
    """
    saved_files = {}
    for f in PRED_DIR.glob('*.npz'):
        stem = f.stem  # e.g. 2025-08-19_vol50_morning_afternoon
        # Split date (first 10 chars) from rest
        date = stem[:10]  # 2025-08-19
        rest = stem[11:]  # vol50_morning_afternoon
        # Split vol gate from time filter
        rest_parts = rest.split('_', 1)  # ['vol50', 'morning_afternoon']
        if len(rest_parts) < 2:
            continue
        vol_str = rest_parts[0]  # vol50
        tf = rest_parts[1]       # morning_afternoon
        try:
            vol_gate = int(vol_str.replace('vol', ''))
        except ValueError:
            continue
        saved_files[(date, vol_gate, tf)] = f
    return saved_files


def run_single_sim(date_str, pred_file, config_label, threshold, hold_ms,
                   latency_ms, trailing_ticks):
    """Run a single Rust sim job with --market-entry."""
    nodash = date_str.replace('-', '')
    mbo_file = MBO_DIR / f'glbx-mdp3-{nodash}.mbo.dbn.zst'
    if not mbo_file.exists():
        mbo_file = MBO_DIR / f'glbx-mdp3-{nodash}.mbo.dbn'
    if not mbo_file.exists():
        return None

    out_file = SIM_OUT_DIR / f'{config_label}_{date_str}.json'

    cmd = [
        str(BINARY),
        '--mbo-file', str(mbo_file),
        '--predictions', str(pred_file),
        '--output', str(out_file),
        '--hold-ms', str(hold_ms),
        '--signal-threshold', str(threshold),
        '--latency-ms', str(latency_ms),
        '--market-entry',   # KEY FLAG: cross the spread
        '--quiet',
    ]
    if trailing_ticks > 0:
        cmd.extend(['--trailing-ticks', str(trailing_ticks)])

    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=600)
        if r.returncode != 0:
            log.warning(f"Sim failed for {config_label}/{date_str}: {r.stderr[:200]}")
            return None
        with open(out_file) as f:
            return json.load(f)
    except subprocess.TimeoutExpired:
        log.warning(f"Sim timed out for {config_label}/{date_str}")
        return None
    except Exception as e:
        log.warning(f"Sim error for {config_label}/{date_str}: {e}")
        return None


def run_sweep(saved_files, workers=6):
    """Run market order sweep."""
    if not BINARY.exists():
        log.error(f"Rust binary not found: {BINARY}")
        return {}

    jobs = []
    for (date, vol_gate, tf), pred_file in saved_files.items():
        if vol_gate not in VOL_GATES or tf not in TIME_FILTERS:
            continue
        for threshold, hold_ms, latency_ms, trailing_ticks, base_label in MARKET_CONFIGS:
            config_label = f'vol{vol_gate}_{tf}_{base_label}'
            jobs.append({
                'date': date,
                'pred_file': pred_file,
                'config_label': config_label,
                'threshold': threshold,
                'hold_ms': hold_ms,
                'latency_ms': latency_ms,
                'trailing_ticks': trailing_ticks,
            })

    log.info(f"Running {len(jobs)} MARKET ORDER sim jobs with {workers} workers")
    log.info(f"  Configs: {len(MARKET_CONFIGS)}")
    log.info(f"  Vol gates: {VOL_GATES}")
    log.info(f"  Dates: {len(set(j['date'] for j in jobs))}")

    results = {}
    done = 0
    t0 = time.time()

    with ThreadPoolExecutor(max_workers=workers) as executor:
        futures = {}
        for job in jobs:
            future = executor.submit(
                run_single_sim,
                job['date'], job['pred_file'], job['config_label'],
                job['threshold'], job['hold_ms'], job['latency_ms'],
                job['trailing_ticks']
            )
            futures[future] = job

        for future in as_completed(futures):
            done += 1
            job = futures[future]
            try:
                result = future.result()
                if result:
                    cl = job['config_label']
                    if cl not in results:
                        results[cl] = {}
                    results[cl][job['date']] = result
            except Exception as e:
                log.warning(f"Job failed: {e}")

            if done % 50 == 0:
                elapsed = time.time() - t0
                rate = done / elapsed
                remaining = (len(jobs) - done) / max(rate, 0.01)
                log.info(f"  [{done}/{len(jobs)}] {rate:.1f} jobs/s, ~{remaining:.0f}s remaining")

    elapsed = time.time() - t0
    log.info(f"Market order sweep complete: {done} jobs in {elapsed:.1f}s")
    return results


def aggregate_and_report(results):
    """Aggregate and report market order results."""
    log.info("\n" + "=" * 80)
    log.info("CNN MARKET ORDER -> RUST MBO SIM RESULTS")
    log.info("(100% fill rate, paying spread on entry)")
    log.info("=" * 80)

    summary = []

    for config_label, date_results in sorted(results.items()):
        total_pnl = 0.0
        total_trades = 0
        total_signals = 0
        total_filled = 0
        total_wins = 0
        daily_pnls = []

        for date_str, res in sorted(date_results.items()):
            day_pnl = res.get('total_pnl_dollars', 0)
            total_pnl += day_pnl
            total_trades += res.get('total_trades', 0)
            total_signals += res.get('total_signals', 0)
            total_filled += res.get('total_filled', 0)
            daily_pnls.append(day_pnl)

            if 'trades' in res:
                for trade in res['trades']:
                    if trade.get('pnl_dollars', 0) > 0:
                        total_wins += 1

        n_days = len(date_results)
        if n_days == 0 or total_trades == 0:
            continue

        win_rate = total_wins / total_trades
        fill_rate = total_filled / total_signals if total_signals > 0 else 0
        avg_daily = np.mean(daily_pnls)
        daily_std = np.std(daily_pnls) if len(daily_pnls) > 1 else 1e-8
        sharpe = (avg_daily / daily_std) * np.sqrt(252) if daily_std > 0 else 0

        cum = np.cumsum(daily_pnls)
        peak = np.maximum.accumulate(cum)
        max_dd = abs((cum - peak).min()) if len(cum) > 0 else 0

        summary.append({
            'config': config_label,
            'total_pnl': total_pnl,
            'n_days': n_days,
            'n_trades': total_trades,
            'fill_rate': fill_rate,
            'win_rate': win_rate,
            'sharpe_daily': sharpe,
            'avg_daily_pnl': avg_daily,
            'max_dd': max_dd,
        })

    summary.sort(key=lambda x: x['total_pnl'], reverse=True)

    log.info(f"\nAll configs by total P&L ({summary[0]['n_days'] if summary else 0} OOS days):")
    log.info(f"{'Config':<50} {'P&L':>10} {'Trades':>7} {'FillR':>6} {'WinR':>6} {'Sharpe':>7} {'MaxDD':>8}")
    log.info("-" * 105)

    for s in summary:
        log.info(
            f"{s['config']:<50} "
            f"${s['total_pnl']:>9,.0f} "
            f"{s['n_trades']:>7} "
            f"{s['fill_rate']:>5.1%} "
            f"{s['win_rate']:>5.1%} "
            f"{s['sharpe_daily']:>7.2f} "
            f"${s['max_dd']:>7,.0f}"
        )

    # Compare with passive limit results
    passive_results = sorted(RESULTS_DIR.glob('cnn_rust_sim_results_*.json'), reverse=True)
    if passive_results and summary:
        try:
            with open(passive_results[0]) as f:
                passive = json.load(f)
            if passive:
                p_best = passive[0]
                m_best = summary[0]
                log.info(f"\n{'='*60}")
                log.info("MARKET vs PASSIVE LIMIT COMPARISON (best each):")
                log.info(f"  {'Metric':<20s} {'Market':>12s} {'Passive':>12s}")
                log.info(f"  {'-'*44}")
                log.info(f"  {'Total P&L':<20s} ${m_best['total_pnl']:>10,.0f} ${p_best['total_pnl']:>10,.0f}")
                log.info(f"  {'Sharpe':<20s} {m_best['sharpe_daily']:>12.2f} {p_best['sharpe_daily']:>12.2f}")
                log.info(f"  {'Trades':<20s} {m_best['n_trades']:>12d} {p_best['n_trades']:>12d}")
                log.info(f"  {'Fill Rate':<20s} {m_best['fill_rate']:>11.1%} {p_best['fill_rate']:>11.1%}")
                log.info(f"  {'Win Rate':<20s} {m_best['win_rate']:>11.1%} {p_best['win_rate']:>11.1%}")
        except Exception as e:
            log.warning(f"Could not compare: {e}")

    out_file = RESULTS_DIR / f'cnn_market_sweep_{_ts}.json'
    with open(out_file, 'w') as f:
        json.dump(summary, f, indent=2, default=str)
    log.info(f"\nResults saved: {out_file}")

    return summary


def main():
    parser = argparse.ArgumentParser(description='CNN Market Order Sweep')
    parser.add_argument('--workers', type=int, default=6)
    args = parser.parse_args()

    log.info("=" * 60)
    log.info("CNN MARKET ORDER Sweep via Rust MBO Sim")
    log.info(f"  Binary: {BINARY}")
    log.info(f"  Predictions: {PRED_DIR}")
    log.info(f"  Workers: {args.workers}")
    log.info("=" * 60)

    saved_files = load_prediction_files()
    if not saved_files:
        log.error(f"No prediction files found in {PRED_DIR}")
        log.error("Run cnn_rust_sim_validation.py first to generate predictions.")
        return

    log.info(f"Loaded {len(saved_files)} prediction files")

    results = run_sweep(saved_files, workers=args.workers)
    if results:
        aggregate_and_report(results)
    else:
        log.error("No sim results.")


if __name__ == '__main__':
    main()
