#!/usr/bin/env python3
"""
CNN Chase/Cancel-Replace Sweep — Test cancel-replace entries through Rust MBO Sim
=================================================================================
Uses the SAME predictions already generated by cnn_rust_sim_validation.py
but runs with --chase-entry flag (reprice to new BBO if it moves away).

This is the middle ground between passive limit (5.7% fill, profitable)
and market orders (100% fill, catastrophic). Chase mode should yield
~15-25% fill rate with potentially better per-trade P&L than market.

Usage:
    python alpha_discovery/cnn_chase_sweep.py
    python alpha_discovery/cnn_chase_sweep.py --workers 8
"""

import sys
import json
import time
import logging
import argparse
import subprocess
import numpy as np
from pathlib import Path
from datetime import datetime
from concurrent.futures import ThreadPoolExecutor, as_completed

LVL3_ROOT = Path(__file__).resolve().parent.parent

import platform
_bin_name = 'fill_sim_cli.exe' if platform.system() == 'Windows' else 'fill_sim_cli'
BINARY = LVL3_ROOT / 'rust_cache_builder' / 'target' / 'release' / _bin_name
MBO_DIR = LVL3_ROOT / 'mbo'
RESULTS_DIR = LVL3_ROOT / 'alpha_discovery' / 'results'
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

# Reuse predictions from CNN passive sim
PRED_DIR = LVL3_ROOT / 'data' / 'processed' / 'cnn_sim_predictions'
SIM_OUT_DIR = LVL3_ROOT / 'data' / 'processed' / 'cnn_chase_sim_results'
SIM_OUT_DIR.mkdir(parents=True, exist_ok=True)

TICK_VALUE = 12.50

_ts = datetime.now().strftime('%Y%m%d_%H%M%S')
_log_file = str(RESULTS_DIR / f'cnn_chase_sweep_{_ts}.log')

log = logging.getLogger('cnn_chase_sweep')
log.setLevel(logging.INFO)
_fh = logging.FileHandler(_log_file, mode='w', encoding='utf-8')
_fh.setFormatter(logging.Formatter('%(asctime)s %(levelname)s: %(message)s'))
log.addHandler(_fh)
_ch = logging.StreamHandler(sys.stdout)
_ch.setFormatter(logging.Formatter('%(asctime)s %(levelname)s: %(message)s'))
log.addHandler(_ch)

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')

# Chase configs — sweep over chase parameters
# Format: (threshold, hold_ms, latency_ms, chase_max_ticks, chase_max_reprices, chase_force_cross, chase_interval_ms, label)
CHASE_CONFIGS = [
    # Conservative chase: 1 tick max, few reprices
    (1.5, 1800000, 0, 1, 3, False, 100, 'chase_1t_3r_conv15_30min'),
    (2.0, 1800000, 0, 1, 3, False, 100, 'chase_1t_3r_conv20_30min'),
    (2.5, 1800000, 0, 1, 3, False, 100, 'chase_1t_3r_conv25_30min'),

    # Moderate chase: 2 ticks, 5 reprices
    (1.5, 1800000, 0, 2, 5, False, 100, 'chase_2t_5r_conv15_30min'),
    (2.0, 1800000, 0, 2, 5, False, 100, 'chase_2t_5r_conv20_30min'),
    (2.5, 1800000, 0, 2, 5, False, 100, 'chase_2t_5r_conv25_30min'),

    # Aggressive chase: 3 ticks, 10 reprices
    (1.5, 1800000, 0, 3, 10, False, 100, 'chase_3t_10r_conv15_30min'),
    (2.0, 1800000, 0, 3, 10, False, 100, 'chase_3t_10r_conv20_30min'),

    # Chase with force-cross on exhaust (hybrid)
    (1.5, 1800000, 0, 1, 3, True, 100, 'chase_1t_3r_FC_conv15_30min'),
    (2.0, 1800000, 0, 1, 3, True, 100, 'chase_1t_3r_FC_conv20_30min'),
    (2.0, 1800000, 0, 2, 5, True, 100, 'chase_2t_5r_FC_conv20_30min'),
    (2.5, 1800000, 0, 2, 5, True, 100, 'chase_2t_5r_FC_conv25_30min'),

    # With latency (more realistic)
    (2.0, 1800000, 10, 2, 5, False, 100, 'chase_2t_5r_conv20_30min_lat10'),
    (2.0, 1800000, 10, 2, 5, True, 100, 'chase_2t_5r_FC_conv20_30min_lat10'),

    # Faster check interval (50ms)
    (2.0, 1800000, 0, 2, 5, False, 50, 'chase_2t_5r_conv20_30min_50ms'),
    (2.0, 1800000, 0, 2, 10, False, 50, 'chase_2t_10r_conv20_30min_50ms'),

    # Unlimited chase (no tick limit, just reprice limit)
    (2.0, 1800000, 0, 0, 5, False, 100, 'chase_unlim_5r_conv20_30min'),
    (2.0, 1800000, 0, 0, 10, False, 100, 'chase_unlim_10r_conv20_30min'),
]

VOL_GATES = [50, 70, 80]
TIME_FILTERS = ['morning_afternoon']


def load_prediction_files():
    """Load existing prediction files from CNN sim."""
    saved_files = {}
    for f in PRED_DIR.glob('*.npz'):
        stem = f.stem
        date = stem[:10]
        rest = stem[11:]
        rest_parts = rest.split('_', 1)
        if len(rest_parts) < 2:
            continue
        vol_str = rest_parts[0]
        tf = rest_parts[1]
        try:
            vol_gate = int(vol_str.replace('vol', ''))
        except ValueError:
            continue
        saved_files[(date, vol_gate, tf)] = f
    return saved_files


def run_single_sim(date_str, pred_file, config_label, threshold, hold_ms,
                   latency_ms, chase_max_ticks, chase_max_reprices,
                   chase_force_cross, chase_interval_ms):
    """Run a single Rust sim job with --chase-entry."""
    nodash = date_str.replace('-', '')
    mbo_file = MBO_DIR / f'glbx-mdp3-{nodash}.mbo.dbn.zst'
    if not mbo_file.exists():
        mbo_file = MBO_DIR / f'glbx-mdp3-{nodash}.mbo.dbn'
    if not mbo_file.exists():
        return None

    out_file = SIM_OUT_DIR / f'{config_label}_{date_str}.json'

    cmd = [
        str(BINARY),
        '--mbo-file', str(mbo_file),
        '--predictions', str(pred_file),
        '--output', str(out_file),
        '--hold-ms', str(hold_ms),
        '--signal-threshold', str(threshold),
        '--latency-ms', str(latency_ms),
        '--chase-entry',
        '--chase-max-ticks', str(chase_max_ticks),
        '--chase-max-reprices', str(chase_max_reprices),
        '--chase-interval-ms', str(chase_interval_ms),
        '--quiet',
    ]
    if chase_force_cross:
        cmd.append('--chase-force-cross')

    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=600)
        if r.returncode != 0:
            log.warning(f"Sim failed for {config_label}/{date_str}: {r.stderr[:200]}")
            return None
        with open(out_file) as f:
            return json.load(f)
    except subprocess.TimeoutExpired:
        log.warning(f"Sim timed out for {config_label}/{date_str}")
        return None
    except Exception as e:
        log.warning(f"Sim error for {config_label}/{date_str}: {e}")
        return None


def run_sweep(saved_files, workers=6):
    """Run chase sweep."""
    if not BINARY.exists():
        log.error(f"Rust binary not found: {BINARY}")
        return {}

    jobs = []
    for (date, vol_gate, tf), pred_file in saved_files.items():
        if vol_gate not in VOL_GATES or tf not in TIME_FILTERS:
            continue
        for (threshold, hold_ms, latency_ms, chase_max_ticks, chase_max_reprices,
             chase_force_cross, chase_interval_ms, base_label) in CHASE_CONFIGS:
            config_label = f'vol{vol_gate}_{tf}_{base_label}'
            jobs.append({
                'date': date,
                'pred_file': pred_file,
                'config_label': config_label,
                'threshold': threshold,
                'hold_ms': hold_ms,
                'latency_ms': latency_ms,
                'chase_max_ticks': chase_max_ticks,
                'chase_max_reprices': chase_max_reprices,
                'chase_force_cross': chase_force_cross,
                'chase_interval_ms': chase_interval_ms,
            })

    log.info(f"Running {len(jobs)} CHASE sim jobs with {workers} workers")
    log.info(f"  Configs: {len(CHASE_CONFIGS)}")
    log.info(f"  Vol gates: {VOL_GATES}")
    log.info(f"  Dates: {len(set(j['date'] for j in jobs))}")

    results = {}
    done = 0
    t0 = time.time()

    with ThreadPoolExecutor(max_workers=workers) as executor:
        futures = {}
        for job in jobs:
            future = executor.submit(
                run_single_sim,
                job['date'], job['pred_file'], job['config_label'],
                job['threshold'], job['hold_ms'], job['latency_ms'],
                job['chase_max_ticks'], job['chase_max_reprices'],
                job['chase_force_cross'], job['chase_interval_ms']
            )
            futures[future] = job

        for future in as_completed(futures):
            done += 1
            job = futures[future]
            try:
                result = future.result()
                if result:
                    cl = job['config_label']
                    if cl not in results:
                        results[cl] = {}
                    results[cl][job['date']] = result
            except Exception as e:
                log.warning(f"Job failed: {e}")

            if done % 50 == 0:
                elapsed = time.time() - t0
                rate = done / elapsed
                remaining = (len(jobs) - done) / max(rate, 0.01)
                log.info(f"  [{done}/{len(jobs)}] {rate:.1f} jobs/s, ~{remaining:.0f}s remaining")

    elapsed = time.time() - t0
    log.info(f"Chase sweep complete: {done} jobs in {elapsed:.1f}s")
    return results


def aggregate_and_report(results):
    """Aggregate and report chase results."""
    log.info("\n" + "=" * 90)
    log.info("CNN CHASE/CANCEL-REPLACE -> RUST MBO SIM RESULTS")
    log.info("(Passive entry with BBO-chasing reprices)")
    log.info("=" * 90)

    summary = []

    for config_label, date_results in sorted(results.items()):
        total_pnl = 0.0
        total_trades = 0
        total_signals = 0
        total_filled = 0
        total_cancelled = 0
        total_wins = 0
        daily_pnls = []

        for date_str, res in sorted(date_results.items()):
            day_pnl = res.get('total_pnl_dollars', 0)
            total_pnl += day_pnl
            total_trades += res.get('total_trades', 0)
            total_signals += res.get('total_signals', 0)
            total_filled += res.get('total_filled', 0)
            total_cancelled += res.get('total_cancelled', 0)
            daily_pnls.append(day_pnl)

            if 'trades' in res:
                for trade in res['trades']:
                    if trade.get('pnl_dollars', 0) > 0:
                        total_wins += 1

        n_days = len(date_results)
        if n_days == 0 or total_trades == 0:
            continue

        win_rate = total_wins / total_trades
        fill_rate = total_filled / total_signals if total_signals > 0 else 0
        cancel_rate = total_cancelled / (total_filled + total_cancelled) if (total_filled + total_cancelled) > 0 else 0
        avg_daily = np.mean(daily_pnls)
        daily_std = np.std(daily_pnls) if len(daily_pnls) > 1 else 1e-8
        sharpe = (avg_daily / daily_std) * np.sqrt(252) if daily_std > 0 else 0

        cum = np.cumsum(daily_pnls)
        peak = np.maximum.accumulate(cum)
        max_dd = abs((cum - peak).min()) if len(cum) > 0 else 0

        summary.append({
            'config': config_label,
            'total_pnl': total_pnl,
            'n_days': n_days,
            'n_trades': total_trades,
            'fill_rate': fill_rate,
            'cancel_rate': cancel_rate,
            'win_rate': win_rate,
            'sharpe_daily': sharpe,
            'avg_daily_pnl': avg_daily,
            'max_dd': max_dd,
        })

    summary.sort(key=lambda x: x['total_pnl'], reverse=True)

    log.info(f"\nAll configs by total P&L ({summary[0]['n_days'] if summary else 0} OOS days):")
    log.info(f"{'Config':<55} {'P&L':>10} {'Trades':>7} {'FillR':>6} {'CnclR':>6} {'WinR':>6} {'Sharpe':>7} {'MaxDD':>8}")
    log.info("-" * 115)

    for s in summary:
        log.info(
            f"{s['config']:<55} "
            f"${s['total_pnl']:>9,.0f} "
            f"{s['n_trades']:>7} "
            f"{s['fill_rate']:>5.1%} "
            f"{s['cancel_rate']:>5.1%} "
            f"{s['win_rate']:>5.1%} "
            f"{s['sharpe_daily']:>7.2f} "
            f"${s['max_dd']:>7,.0f}"
        )

    # Compare with passive limit results
    passive_results = sorted(RESULTS_DIR.glob('cnn_rust_sim_results_*.json'), reverse=True)
    if passive_results and summary:
        try:
            with open(passive_results[0]) as f:
                passive = json.load(f)
            if passive:
                p_best = passive[0]
                m_best = summary[0]
                log.info(f"\n{'='*65}")
                log.info("CHASE vs PASSIVE LIMIT COMPARISON (best each):")
                log.info(f"  {'Metric':<20s} {'Chase':>12s} {'Passive':>12s}")
                log.info(f"  {'-'*44}")
                log.info(f"  {'Total P&L':<20s} ${m_best['total_pnl']:>10,.0f} ${p_best['total_pnl']:>10,.0f}")
                log.info(f"  {'Sharpe':<20s} {m_best['sharpe_daily']:>12.2f} {p_best['sharpe_daily']:>12.2f}")
                log.info(f"  {'Trades':<20s} {m_best['n_trades']:>12d} {p_best['n_trades']:>12d}")
                log.info(f"  {'Fill Rate':<20s} {m_best['fill_rate']:>11.1%} {p_best['fill_rate']:>11.1%}")
                log.info(f"  {'Win Rate':<20s} {m_best['win_rate']:>11.1%} {p_best['win_rate']:>11.1%}")
        except Exception as e:
            log.warning(f"Could not compare: {e}")

    out_file = RESULTS_DIR / f'cnn_chase_sweep_{_ts}.json'
    with open(out_file, 'w') as f:
        json.dump(summary, f, indent=2, default=str)
    log.info(f"\nResults saved: {out_file}")

    return summary


def main():
    parser = argparse.ArgumentParser(description='CNN Chase/Cancel-Replace Sweep')
    parser.add_argument('--workers', type=int, default=6)
    args = parser.parse_args()

    log.info("=" * 60)
    log.info("CNN CHASE/CANCEL-REPLACE Sweep via Rust MBO Sim")
    log.info(f"  Binary: {BINARY}")
    log.info(f"  Predictions: {PRED_DIR}")
    log.info(f"  Workers: {args.workers}")
    log.info("=" * 60)

    saved_files = load_prediction_files()
    if not saved_files:
        log.error(f"No prediction files found in {PRED_DIR}")
        log.error("Run cnn_rust_sim_validation.py first to generate predictions.")
        return

    log.info(f"Loaded {len(saved_files)} prediction files")

    results = run_sweep(saved_files, workers=args.workers)
    if results:
        aggregate_and_report(results)
    else:
        log.error("No sim results.")


if __name__ == '__main__':
    main()
