#!/usr/bin/env python3
"""
Parallel Rust fill_sim_cli runner for EventTransformer predictions on Jupiter.

Uses EventTransformer OOS predictions (IC ~0.11, generated by extract_event_predictions.py).
Only tests dates where ET predictions exist (Jul 22 - Aug 13 = 17 days).
Tests multiple configs and thresholds.

Run on Jupiter: python3 /home/jupiter/run_rust_et_sim.py
Upload first:    python utils/ssh_exec.py upload run_rust_et_sim.py /home/jupiter/run_rust_et_sim.py
"""
import subprocess
import json
import time
from pathlib import Path
from concurrent.futures import ProcessPoolExecutor, as_completed

BINARY     = "/home/jupiter/lvl3quant/rust_cache_builder/target/release/fill_sim_cli"
MBO_DIR    = Path("/home/jupiter/lvl3quant/data/mbo")
CONFIG_DIR = Path("/home/jupiter/lvl3quant/production/configs")
PRED_DIR   = Path("/home/jupiter/lvl3quant/data/processed/event_predictions")
OUT_BASE   = Path("/home/jupiter/lvl3quant/production/results/et_sim")
LOG_DIR    = OUT_BASE / "logs"

# Configs to test: based on earlier manual testing
# Best fills came from h15000_t8_s8 and h20000_t8_s7
# Testing a wider range now that we have better predictions
CONFIGS = [
    "h15000_t8_s8",   # hold=15s, trailing=8t, signal_flip=8t
    "h20000_t8_s7",   # hold=20s, trailing=8t, signal_flip=7t
    "h30000_t4_s7",   # hold=30s, trailing=4t, signal_flip=7t
    "h10000_t5_default",  # hold=10s (default), trailing=5t
]

# ET predictions are already raw logits, threshold to control trade density
# Lower thresholds = more trades, higher = higher confidence signals only
THRESHOLDS = [0.3, 0.5, 0.7, 0.9]

# Dates with EventTransformer OOS predictions (Jul 22 - Aug 13 = 17 active days)
# Only dates that have both MBO file AND ET prediction file
DATES = [
    "2025-07-22", "2025-07-23", "2025-07-24", "2025-07-25",
    "2025-07-28", "2025-07-29", "2025-07-30", "2025-07-31",
    "2025-08-01", "2025-08-04", "2025-08-05", "2025-08-06",
    "2025-08-07", "2025-08-08", "2025-08-11", "2025-08-12", "2025-08-13",
]

OUT_BASE.mkdir(parents=True, exist_ok=True)
LOG_DIR.mkdir(parents=True, exist_ok=True)


def apply_threshold(pred_dir, date_str, thresh):
    """
    Apply threshold to ET predictions and save a thresholded NPZ.
    Returns path to thresholded NPZ, or None on error.
    """
    import numpy as np
    src = pred_dir / f"{date_str}_predictions.npz"
    if not src.exists():
        return None

    thresh_dir = pred_dir.parent / "event_predictions_thresh" / f"thresh_{thresh}"
    thresh_dir.mkdir(parents=True, exist_ok=True)
    out = thresh_dir / f"{date_str}_predictions.npz"

    if out.exists():
        return out

    d = np.load(str(src))
    preds = d["predictions"].copy()
    preds[abs(preds) <= thresh] = 0.0
    np.savez_compressed(str(out), predictions=preds)
    return out


def run_one(args):
    """Run one fill_sim_cli job. Returns (job_id, success, summary)."""
    cfg, thresh, date_str = args

    date_raw = date_str.replace("-", "")
    mbo_file = MBO_DIR / f"glbx-mdp3-{date_raw}.mbo.dbn"
    cfg_file = CONFIG_DIR / f"{cfg}.json"

    thresh_str = str(thresh).replace(".", "")
    out_dir  = OUT_BASE / f"{cfg}_t{thresh_str}"
    out_dir.mkdir(exist_ok=True)
    out_file = out_dir / f"{date_str}.json"
    log_file = LOG_DIR / f"{cfg}_t{thresh_str}_{date_str}.log"

    job_id = f"{cfg}_t{thresh}_{date_str}"

    # Skip if already done
    if out_file.exists():
        try:
            d = json.loads(out_file.read_text())
            pnl = d["summary"]["total_pnl_dollars"]
            return (job_id, True, f"SKIP (done, PnL=${pnl:.1f})")
        except Exception:
            pass

    # Check MBO file
    if not mbo_file.exists():
        return (job_id, False, f"SKIP (no MBO: {mbo_file.name})")

    # Apply threshold to ET predictions
    pred_file = apply_threshold(PRED_DIR, date_str, thresh)
    if pred_file is None:
        return (job_id, False, f"SKIP (no ET predictions for {date_str})")

    start = time.time()
    cmd = [
        BINARY,
        "--mbo-file",    str(mbo_file),
        "--predictions", str(pred_file),
        "--output",      str(out_file),
        "--config",      str(cfg_file),
        "--quiet",
    ]

    try:
        with open(log_file, "w") as lf:
            result = subprocess.run(cmd, stdout=lf, stderr=subprocess.STDOUT, timeout=600)
    except subprocess.TimeoutExpired:
        return (job_id, False, f"TIMEOUT (>600s)")

    elapsed = time.time() - start

    if result.returncode != 0:
        return (job_id, False, f"FAILED (exit={result.returncode}, {elapsed:.0f}s)")

    try:
        d = json.loads(out_file.read_text())
        s = d["summary"]
        msg = (
            f"PnL=${s['total_pnl_dollars']:.1f}, "
            f"trades={s['total_trades']}, "
            f"fill={s['fill_rate']*100:.0f}%, "
            f"wr={s['win_rate']*100:.0f}%, "
            f"sharpe={s['sharpe_per_trade']:.3f}, "
            f"t={elapsed:.0f}s"
        )
        return (job_id, True, msg)
    except Exception as e:
        return (job_id, False, f"PARSE ERROR: {e}")


def main():
    # Build job list
    jobs = []
    for cfg in CONFIGS:
        for thresh in THRESHOLDS:
            for date_str in DATES:
                jobs.append((cfg, thresh, date_str))

    total = len(jobs)
    print(f"ET Sim Run")
    print(f"Total jobs: {total} ({len(CONFIGS)} configs x {len(THRESHOLDS)} thresholds x {len(DATES)} dates)")
    print(f"Predictions: {PRED_DIR}")
    print(f"Configs: {CONFIGS}")
    print(f"Thresholds: {THRESHOLDS}")
    print()

    MAX_WORKERS = 8
    completed = 0
    failed    = 0
    skipped   = 0

    with ProcessPoolExecutor(max_workers=MAX_WORKERS) as executor:
        futures = {executor.submit(run_one, job): job for job in jobs}
        for future in as_completed(futures):
            job_id, success, msg = future.result()
            completed += 1
            if "SKIP" in msg:
                skipped += 1
            elif not success:
                failed += 1
                print(f"[{completed}/{total}] FAIL  {job_id}: {msg}", flush=True)
            else:
                print(f"[{completed}/{total}] OK    {job_id}: {msg}", flush=True)

    print()
    print(f"Done. {completed} total, {failed} failed, {skipped} skipped")
    print()

    # Aggregate results
    print("=" * 70)
    print("AGGREGATE RESULTS (sorted by total PnL)")
    print("=" * 70)

    results = []
    for cfg in CONFIGS:
        for thresh in THRESHOLDS:
            thresh_str = str(thresh).replace(".", "")
            out_dir = OUT_BASE / f"{cfg}_t{thresh_str}"
            json_files = sorted(out_dir.glob("*.json"))
            if not json_files:
                continue

            total_pnl = 0.0
            total_trades = 0
            total_filled = 0
            total_posted = 0
            total_wins   = 0
            days_ok = 0

            for jf in json_files:
                try:
                    d = json.loads(jf.read_text())
                    s = d["summary"]
                    total_pnl    += s["total_pnl_dollars"]
                    total_trades += s["total_trades"]
                    total_filled += s["total_filled"]
                    total_posted += s["total_posted"]
                    if s["total_trades"] > 0:
                        total_wins += int(s["win_rate"] * s["total_trades"])
                    days_ok += 1
                except Exception:
                    pass

            if days_ok == 0:
                continue

            avg_pnl   = total_pnl / days_ok
            fill_rate = total_filled / total_posted if total_posted else 0
            win_rate  = total_wins / total_trades if total_trades else 0

            results.append({
                "cfg": cfg, "thresh": thresh, "days": days_ok,
                "total_pnl": total_pnl, "avg_pnl": avg_pnl,
                "trades": total_trades, "fill_rate": fill_rate,
                "win_rate": win_rate,
            })

    results.sort(key=lambda x: x["total_pnl"], reverse=True)
    for i, r in enumerate(results, 1):
        print(f"\n#{i:2d} {r['cfg']} thresh={r['thresh']} ({r['days']}/{len(DATES)} days):")
        print(f"     Total PnL:   ${r['total_pnl']:+,.0f}")
        print(f"     Avg/day:     ${r['avg_pnl']:+,.0f}")
        print(f"     Trades:      {r['trades']} ({r['trades']//max(r['days'],1)}/day avg)")
        print(f"     Fill rate:   {r['fill_rate']*100:.1f}%")
        print(f"     Win rate:    {r['win_rate']*100:.1f}%")


if __name__ == "__main__":
    main()
