#!/usr/bin/env python3
"""HC #477 R3 / HC #478 R2 — Alpha label source audit.

Purpose: confirm where the long-horizon label-zero bug originates.

For each alpha_labels NPZ in data/processed/mbo_events_smart_v3_alpha_labels/:
  - List keys present.
  - For each numeric key: shape, dtype, n_NaN, n_zero, min, max, mean, std.
  - Specifically flag whether `log_ret_60s` and `log_ret_5min` keys are
    MISSING vs PRESENT-BUT-ALL-NAN vs PRESENT-BUT-ALL-ZERO.

Outputs:
  reports/hc477_alpha_label_audit/per_file.jsonl
  reports/hc477_alpha_label_audit/summary.md

Diagnostic only. No mutations. Per HC #478 R3 (data ingestion is auditable).
"""

import json
import os
import sys
from datetime import datetime
from pathlib import Path

import numpy as np

ROOT = Path("/home/jupiter/Lvl3Quant")
SRC = ROOT / "data/processed/mbo_events_smart_v3_alpha_labels"
OUT_DIR = ROOT / "reports/hc477_alpha_label_audit"
OUT_DIR.mkdir(parents=True, exist_ok=True)

LONG_HORIZON_KEYS = ["log_ret_60s", "log_ret_5min"]
ALL_RETURN_KEYS = ["log_ret_1s", "log_ret_5s", "log_ret_10s", "log_ret_30s",
                   "log_ret_60s", "log_ret_5min"]


def summarize_array(a):
    a = np.asarray(a)
    if a.dtype.kind in ("f", "i", "u"):
        a_f = a.astype(float, copy=False)
        n = a_f.size
        n_nan = int(np.isnan(a_f).sum())
        n_zero = int(((a_f == 0) & ~np.isnan(a_f)).sum())
        finite = a_f[np.isfinite(a_f)]
        return {
            "n": n,
            "n_nan": n_nan,
            "n_zero": n_zero,
            "n_finite": int(finite.size),
            "min": float(finite.min()) if finite.size else None,
            "max": float(finite.max()) if finite.size else None,
            "mean": float(finite.mean()) if finite.size else None,
            "std": float(finite.std()) if finite.size else None,
        }
    return {"n": int(a.size), "dtype": str(a.dtype)}


def main():
    files = sorted(SRC.glob("*_alpha_labels.npz"))
    print(f"[audit] {len(files)} alpha-label files", flush=True)

    per_file_path = OUT_DIR / "per_file.jsonl"
    summary_counts = {
        "missing": {k: 0 for k in ALL_RETURN_KEYS},
        "all_nan": {k: 0 for k in ALL_RETURN_KEYS},
        "all_zero": {k: 0 for k in ALL_RETURN_KEYS},
        "valid": {k: 0 for k in ALL_RETURN_KEYS},
    }
    all_keys_union = set()

    with open(per_file_path, "w") as fout:
        for i, f in enumerate(files):
            try:
                d = np.load(f, allow_pickle=True)
                keys = list(d.files)
                all_keys_union.update(keys)
                rec = {"file": f.name, "keys": keys, "stats": {}}
                for k in ALL_RETURN_KEYS:
                    if k not in keys:
                        rec[f"flag_{k}"] = "MISSING"
                        summary_counts["missing"][k] += 1
                        continue
                    s = summarize_array(d[k])
                    rec["stats"][k] = s
                    if s.get("n_finite", 0) == 0:
                        rec[f"flag_{k}"] = "ALL_NAN"
                        summary_counts["all_nan"][k] += 1
                    elif s.get("n_zero", 0) == s.get("n", 1) - s.get("n_nan", 0):
                        rec[f"flag_{k}"] = "ALL_ZERO"
                        summary_counts["all_zero"][k] += 1
                    else:
                        rec[f"flag_{k}"] = "VALID"
                        summary_counts["valid"][k] += 1
                fout.write(json.dumps(rec) + "\n")
                if (i + 1) % 20 == 0:
                    print(f"[audit] {i+1}/{len(files)}", flush=True)
            except Exception as e:
                fout.write(json.dumps({"file": f.name, "error": str(e)}) + "\n")

    md = ["# HC #477 / HC #478 — Alpha Label Source Audit",
          f"\nGenerated: {datetime.utcnow().isoformat()}",
          f"\nSource: `{SRC}`",
          f"\nN files audited: {len(files)}",
          "\n## Key presence + validity per horizon\n",
          "| Horizon | MISSING | ALL_NAN | ALL_ZERO | VALID |",
          "|---------|---------|---------|----------|-------|"]
    for k in ALL_RETURN_KEYS:
        md.append(f"| `{k}` | {summary_counts['missing'][k]} | "
                  f"{summary_counts['all_nan'][k]} | "
                  f"{summary_counts['all_zero'][k]} | "
                  f"{summary_counts['valid'][k]} |")

    md.append("\n## Union of all keys present in NPZs\n")
    md.append("```")
    for k in sorted(all_keys_union):
        md.append(k)
    md.append("```")

    md.append("\n## Interpretation per HC #477 R3\n")
    md.append("- MISSING = key never generated by upstream label builder → fix the builder.")
    md.append("- ALL_NAN = key generated but all values invalid (e.g., end-of-day windowing) → fix windowing or use prior-day carry.")
    md.append("- ALL_ZERO = key generated and zero-filled instead of NaN-filled → fix sentinel.")
    md.append("- VALID = key produces real signal → safe to train on.")

    (OUT_DIR / "summary.md").write_text("\n".join(md))
    print(f"[audit] wrote {OUT_DIR/'summary.md'}", flush=True)
    print(json.dumps(summary_counts, indent=2), flush=True)


if __name__ == "__main__":
    main()
